"use strict";

exports.__esModule = true;
exports.UPDATE_RECORD = exports.SET_SUBSCRIPTIONS = exports.SET_RECORDS = exports.DELETE_SUBSCRIPTION = exports.DELETE_RECORDS = exports.DELETE_RECORD = exports.ADD_SUBSCRIPTION = exports.ADD_RECORDS = exports.ADD_RECORD = void 0;
const SET_RECORDS = exports.SET_RECORDS = 'SET_RECORDS';
const ADD_RECORD = exports.ADD_RECORD = 'ADD_RECORD';
const ADD_RECORDS = exports.ADD_RECORDS = 'ADD_RECORDS';
const UPDATE_RECORD = exports.UPDATE_RECORD = 'UPDATE_RECORD';
const DELETE_RECORD = exports.DELETE_RECORD = 'DELETE_RECORD';
const DELETE_RECORDS = exports.DELETE_RECORDS = 'DELETE_RECORDS';
const SET_SUBSCRIPTIONS = exports.SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';
const ADD_SUBSCRIPTION = exports.ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
const DELETE_SUBSCRIPTION = exports.DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';